version: '3'
services:
  java-WebRussiaApplication:
    image: webofculturavaluesofrussiaapplication:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
